name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Create pre-commit config
      run: |
        cat << EOF > .pre-commit-config.yaml
        repos:
        -   repo: https://github.com/psf/black
            rev: 22.10.0
            hooks:
            -   id: black
        -   repo: https://github.com/PyCQA/flake8
            rev: 5.0.4
            hooks:
            -   id: flake8
                args: [--max-line-length=127, --ignore=E302,W293,W292,E501,F401,F841]
        -   repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.3.0
            hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: check-added-large-files
        EOF
    - name: Run pre-commit
      run: pre-commit run --all-files
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply pre-commit automatic fixes
        branch: ${{ github.head_ref }}
