name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pre-commit
    
    - name: Run Black
      run: black .
    
    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=E302,W293,W292,E501,F401,F841
      continue-on-error: true
    
    - name: Create pre-commit config
      run: |
        cat << EOF > .pre-commit-config.yml
        repos:
        -   repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.3.0
            hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: check-added-large-files
        EOF
    
    - name: Run pre-commit
      run: pre-commit run --all-files --config .pre-commit-config.yml
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic formatting changes
        branch: ${{ github.head_ref }}
