name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
    
    - name: Create .flake8 configuration
      run: |
        echo "[flake8]
        max-line-length = 100
        ignore = W293, E302, W292
        exclude =
            .git,
            __pycache__,
            build,
            dist,
            .venv
        per-file-ignores =
            __init__.py:F401
            tests/*:F841" > .flake8
    
    - name: Run Black
      run: black .
    
    - name: Run flake8
      run: flake8 --config=.flake8 .
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic formatting changes
        branch: ${{ github.head_ref }}
        
    - name: Check for remaining issues
      run: |
        if [ ${{ job.status }} == 'failure' ]; then
          echo "::warning::Linting or formatting issues remain. Please check the job logs for details."
        fi
