name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
    
    - name: Format code
      run: black .
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}
        file_pattern: .
        commit_options: '--no-verify'
